### ISSUE TITLE
Scrolling with large datasets

### ISSUE THREAD

**Issue by dpastorgalan** [Jollyfant/Paleomagnetism.org#6]
Never thought about it, but, now that I am playing with the dataset of Iberia embedded in the Beta, I feel like for such datasets the menu is not so practical, as it looked for smaller datasets.

Would it be very complicated to get a larger window, maybe in the lateral always displayed (like the steps in the interpretation portal)

**Comment by Jollyfant** [comment]
Do you mean the select menus?

**Comment by dpastorgalan** [comment]
Yes, the select menus are kind of narrow, and requires a lot of scrolling and clicking. I do not know which is the best solution. I'd like seeing all the samples in the side, with the possibility of select them saving one click (to open the menu), and a lot of scroll. But I do not know if this is possible.

**Comment by Jollyfant** [comment]
Scroll menu now scales with number of sites up to a maximum height of 400px

![show](https://cloud.githubusercontent.com/assets/10128244/15370670/4405c720-1d38-11e6-95fd-40915abffb73.png)
