### ISSUE TITLE
Still ALPHA.1509.3??

### ISSUE THREAD

**Issue by dpastorgalan** [Jollyfant/Paleomagnetism.org#7]
Is this still ALPHA version?

I think after publishing, it should be kept aside (or call it stable version vs. development here in Github or something)

**Comment by Jollyfant** [comment]
I'll keep it as Alpha until I release the next version I mailed you some time about. Whether we call that Beta or 1.0 doesn't really matter. I'd go for 1.0 since the paper is out now.
